MonoFont = "noto-mono"

[[Fonts]]
Name = "noto"
  [[Fonts.StyleDefinitions]]
  Style    = "regular"
  FilePath = "NotoSans-Regular.ttf"
  [[Fonts.StyleDefinitions]]
  Style    = "bold"
  FilePath = "NotoSans-Bold.ttf"
  [[Fonts.StyleDefinitions]]
  Style    = "italic"
  FilePath = "NotoSans-Italic.ttf"
  [[Fonts.StyleDefinitions]]
  Style    = "bold+italic"
  FilePath = "NotoSans-BoldItalic.ttf"

[[Fonts]]
Name = "noto-mono"
  [[Fonts.StyleDefinitions]]
  Style    = "regular"
  FilePath = "NotoMono-Regular.ttf"
